name: {{workflowName}}
on:
  push:
    branches:
      - {{branch}}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run Node.js tests
        run: npm test

      - name: Set up Java environment
        if: ${{ contains(steps.language.outputs.result, 'java') }}
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin' # Options: temurin, zulu, adopt, etc.

      - name: Cache Maven dependencies
        if: ${{ contains(steps.language.outputs.result, 'java') }}
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Install Maven dependencies
        if: ${{ contains(steps.language.outputs.result, 'java') }}
        run: mvn dependency:resolve

      - name: Run Maven tests
        if: ${{ contains(steps.language.outputs.result, 'java') }}
        run: mvn test
